name: Push Docker Image to ECR

on:
  push:
    branches: [deploy/prod]

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 957118235304.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: lastminute-backend
  ECS_CLUSTER: last-minute-prod
  ECS_SERVICE: backend
  CONTAINER_NAME: last-minute-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo (if needed)
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          IMAGE_TAG=latest
          SHA_TAG=${GITHUB_SHA}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "SHA_TAG=$SHA_TAG" >> $GITHUB_ENV
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:$SHA_TAG ./backend

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$SHA_TAG